name: flutter_application_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  image_picker: ^0.8.4+10
  firebase_storage: ^10.2.6
  google_sign_in: ^5.2.4
  flutter_signin_button: ^2.0.0
  salomon_bottom_bar: ^3.3.0
  carousel_slider: ^4.0.0
  google_fonts: ^2.3.1
  material_design_icons_flutter: ^5.0.6595
  cached_network_image: ^3.2.1


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/placeholder.jpg

